Asher_admin/urls.py
from django.urls import path
from .views import (
    #Admin Dashboard
    AdminDashboardView,
        
    # Users URLs
    UsersView,NewUserView,EditUserView,
    
    # Booking URLs
    BookingListView,
    
    # Package URLs
    PackageAddView,PackageActiveView,PackageExpiredView,PackagePendingView,
    
    # Comments URLs
    CommentsView, 
    
    # WishList URLs
    WishListView,

)

app_name = 'Asher_admin'

urlpatterns = [
    path('', AdminDashboardView.as_view(), name='dashboard'),
]

#Users URLS

urlpatterns += [
    path('users/', UsersView.as_view(), name='users'),
    path('new_user/', NewUserView.as_view(), name='new-user'),
    path('edit_user/', EditUserView.as_view(), name='edit-user'),
    ]



#Booking URLs
urlpatterns += [
    path('bookings/', BookingListView.as_view(), name='bookings'),
    ]

#Packages URLs

urlpatterns += [
    path('package-add/', PackageAddView.as_view(), name='package-add'),
    path('package-active/', PackageActiveView.as_view(), name='package-active'),
    path('package-expired/', PackageExpiredView.as_view(), name='package-expired'),
    path('package-pending/', PackagePendingView.as_view(), name='package-pending'),
    ]

#Comments Urls

urlpatterns += [
    path('comments/', CommentsView.as_view(), name='comments'),
    ]


#WishList URLs
urlpatterns += [
    path('wish-list/', WishListView.as_view(), name='wish-list'),
    ]

Asher_tour/urls.py
from django.contrib import admin
from django.urls import path,include, re_path as static_helper
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from system_db.ad_package import package_admin_site
from django.conf.urls import handler404
from .errors import error_404_view

# Custom error handlers
handler404 = error_404_view


urlpatterns = [
    path('', include('Home.urls')),
    path('admin/', include('Asher_admin.urls')),
    path('auth/', include('authentication.urls')),
    path('adm/', admin.site.urls),
    path('package-adm/', package_admin_site.urls),
]

# #SERVE STATIC FILES
# urlpatterns += [
#     static_helper(r'^media/(?P<path> *)$', serve, {'document': settings.MEDIA_ROOT}),
#     static_helper(r'^static/(?P<path> *)$', serve, {'document': settings.STATIC_ROOT})
#     ]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



Home/urls.py
from django.urls import path
from .views import *

app_name = 'Home'

urlpatterns = [
    path('', HomeSiteView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('service/', OurServiceView.as_view(), name='service'),
    path('tour-packages/', TourPackagesView.as_view(), name='tour-packages'),
    path('tour-package/details/<slug:slug>-<int:pk>', TourPackageDetails.as_view(), name='package-detail'),
    path('package-offers/', OfferView.as_view(), name='package-offers'),
]


authentication/urls.py
from django.urls import path
from .views import LoginView, ForgotView

app_name = 'authentication'

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('forgot-password/', ForgotView.as_view(), name='forgot'),
]



authentication/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import EmailValidator
from PIL import Image  # For handling image processing
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField
from django.db.models.constraints import UniqueConstraint, CheckConstraint
from django.db.models import Q

class UserManager(BaseUserManager):
    """
    Custom manager for User.
    """
    def create_user(self, email, first_name, last_name, phone, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            first_name=first_name,
            last_name=last_name,
            phone=phone,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    
    def create_superuser(self, email, first_name, last_name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_verified', True)
    
        country = extra_fields.get('country', 'RW')  # Default to 'RW' if not provided
        if len(country) != 2:
            raise ValueError("Country code must be a valid 2-character ISO code.")
    
        return self.create_user(email, first_name, last_name, phone, password, **extra_fields)



    
class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom user model with custom fields.
    """
    email = models.EmailField(unique=True, validators=[EmailValidator()])
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = PhoneNumberField(unique=True, region="RW")
    country = CountryField(blank_label='Select Country',default='RW')
    picture = models.ImageField(upload_to='profile_pictures/', null=True, blank=True)
    active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)  # Renamed from 'status' to 'is_verified'
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(null=True, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone', 'country']
    
    class Meta:
        ordering = ["-date_joined"]  # Newest users first
        indexes = [
            models.Index(fields=["is_staff", "active"], name="idx_is_staff_active"),
            models.Index(fields=["is_admin", "active"], name="idx_is_admin_active"),
            models.Index(fields=["is_customer", "country"], name="idx_is_customer_country"),
            models.Index(fields=["-date_joined"], name="idx_date_joined_desc"),
        ]
        constraints = [
            UniqueConstraint(fields=["email"], name="unique_email_constraint"),
            UniqueConstraint(fields=["phone"], name="unique_phone_constraint"),
            UniqueConstraint(fields=["email", "phone"], name="unique_email_phone"),
            CheckConstraint(
                check=Q(active=True) | (Q(is_staff=False) & Q(is_admin=False)),
                name="check_active_for_staff_admin"
            )
        ]

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        if self.picture:
            try:
                img = Image.open(self.picture.path)
                if img.height > 300 or img.width > 300:
                    new_img = (300, 300)
                    img.thumbnail(new_img)
                    img.save(self.picture.path)
            except Exception as e:
                print(f"Error resizing image: {e}")
        super().save(*args, **kwargs)

authentication/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from django.contrib import messages
from .permisions import AdminAuth
from django.urls import reverse_lazy

# Create your views here.

User = get_user_model()

class LoginView(View):
    login_url = reverse_lazy('authentication:login')
    
    def get(self, request):
        return render(request, 'auth/login.html')
    def post(self, request):
        email = request.POST.get('email')
        if email:
           messages.error(request,f"The user with email {email} does not exist")
        elif not email:
           messages.error(request,f"Prease enter your email and password")
        return redirect('authentication:login')
    
class ForgotView(AdminAuth, View):
    login_url = reverse_lazy('authentication:login')
    
    def get(self, request):
        return render(request, 'auth/forgot.html')
    def post(self, request):
        email = request.POST.get('email')
        if email:
           messages.error(request,f"The user with email {email} does not exist")
        elif not email:
           messages.error(request,f"Prease enter your email and password")
        return redirect('authentication:login')
    

    

authentication/templates/base-auth.html
{% load static %}
<!doctype html>
<html lang="en">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap 5 CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vk26BpSX4TVnmsL8Jp1hMjs9+Kr/jD8K21PqQ6YZtWekuw9C07IkvDF6x6EqfxAw" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-G2Qt4YRb8PK+0MLksVyirvNVhXcddffVYkWY3IlOZZJ9EJRAkHmpQvWj9VV1tmxg" crossorigin="anonymous">

    <!-- favicon -->
    <link rel="icon" type="image/png" href="{% static 'admin/assets/images/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'admin/assets/css/bootstrap.min.css' %}" media="all">
    <!-- Fonts Awesome CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin/assets/css/all.min.css' %}">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,400&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,400&display=swap" rel="stylesheet">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'admin/style.css' %}">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- favicon -->
      <link rel="icon" type="image/png" href="../assets/images/favicon.png">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="assets/css/bootstrap.min.css" media="all">
      <!-- Fonts Awesome CSS -->
      <link rel="stylesheet" type="text/css" href="assets/css/all.min.css">
      <!-- google fonts -->
      <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,400&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,400&display=swap" rel="stylesheet">
      <!-- Custom CSS -->
      <link rel="stylesheet" type="text/css" href="{% static 'admin/style.css' %}">
      <title>Travele | Travel & Tour HTML5 template </title>
</head>
<body>
    <style>
        .login-page .login-from-wrap{
            opacity: 0.87;
            border-radius: 10px;
        }
    </style>
    <div class="login-page" style="background-image: url({% static 'convetion.jpg' %});">
    

        <div class="login-from-wrap">
           
           {% block auth_content %}
           
           <form class="login-from">
            <h1 class="site-title">
                <a href="#">
                    <img src="{% static 'admin/assets/images/logo.png' %}" alt="">
                </a>
            </h1>
            
            <div class="form-group">
                <label for="first_name1">User Name</label>
                <input type="text" class="validate">
            </div>
            <div class="form-group">
                <label for="last_name">Password</label>
                <input id="last_name" type="password" class="validate">
            </div>
            <div class="form-group">
                <a class="button-primary" href="{% url 'Asher_admin:dashboard' %}">Login</a>
            </div>
            <a href="{% url 'authentication:forgot' %}" class="for-pass">Forgot Password?</a>
        </form>
           {% endblock auth_content %}
        </div>
    </div>

    <!-- *Scripts* -->
    <script defer src="{% static 'admin/assets/js/jquery-3.2.1.min.js' %}"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script defer src="{% static 'admin/assets/js/bootstrap.min.js' %}"></script>
    <script defer src="{% static 'admin/assets/js/canvasjs.min.js'  %}"></script>
    <script defer src="{% static 'admin/assets/js/chart.js' %}"></script>
    <script defer src="{% static 'admin/assets/js/counterup.min.js' %}"></script>
    <script defer src="{% static 'admin/assets/js/jquery.slicknav.js' %}"></script>
    <script defer src="{% static 'admin/assets/js/dashboard-custom.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-64QzU8KZ67NtRuScJ0hWZVRZTiaUJ07ymI9QO8rLBNqVZG/J9OnyQ/jmVD6tpfB+" crossorigin="anonymous"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js" integrity="sha384-oI7mNJlpYEB1C4ZmVOPJ8I9JctJmM+5kDfl6eJji3aE5/EN5txVfqQUSJbR8So9c" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-4ZH+CbNfUTc6U20Pq3u7lhbrjt8tX7pZI6Ty5M7N2i5yZsGFNPEY4PzNJWFFj30D" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-8mXp9JJJJGSvvh2D4hpzIiNTPEtVgfM4CRDRz+PbJ8T3vEhtB5c3bO2t11hgrzAA" crossorigin="anonymous"></script>
    

    <!-- *Scripts* -->
    <script src="assets/js/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/canvasjs.min.js"></script>
    <script src="assets/js/counterup.min.js"></script>
    <script src="assets/js/jquery.slicknav.js"></script>
    <script src="assets/js/dashboard-custom.js"></script>
</body>
</html>